//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

namespace SuddenlyEntertainment
{
	public class ColliderManager : MonoBehaviour
	{
		public List<Collider> Colliders = new List<Collider>();

		void Start()
		{

		}	

		void OnTriggerEnter(Collider collider)
		{
			if(collider.tag != "Projectiles")
			Colliders.Add(collider);
		}

		void OnTriggerExit(Collider collider)
		{
			if(collider.tag != "Projectiles")
			Colliders.Remove(collider);
		}
	}
}

