//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace SuddenlyEntertainment
{
	public interface INetSerializable 
	{
		void Deserialize(string Serial);
		string Serialize();
		
		Dictionary<string, object> NetPrep();
	}
	
}
